version: '3'

services:
  api:
    build:
      context: ./api
      args:
        VALIDATA_CORE_REPO: git+https://git.opendatafrance.net/abulte/validata-core.git@etalab
        VALIDATA_API_REPO: git+https://git.opendatafrance.net/abulte/validata-api.git@etalab
    ports:
      - 5600:5600
    environment:
      - VALIDATA_SCHEMAS_CONFIG=/schemas/schemas.toml
      - BADGE_CONFIG_URL=https://git.opendatafrance.net/validata/validata-badge/raw/master/badge_conf.toml
      - SHIELDS_IO_BASE_URL=https://img.shields.io/
      - SECRET_KEY=p4mBTNEHTbPx
    volumes:
      - /Users/alexandre/Developer/Etalab/schema/schema.data.gouv.fr/:/schemas/
  ui:
    build:
      context: ./ui
      args:
        VALIDATA_CORE_REPO: git+https://git.opendatafrance.net/abulte/validata-core.git@etalab
        VALIDATA_UI_REPO: git+https://git.opendatafrance.net/abulte/validata-ui.git@etalab
    ports:
      - 5601:5601
    environment:
      - VALIDATA_SCHEMAS_CONFIG=/schemas/schemas.toml
      - BADGE_CONFIG_URL=https://git.opendatafrance.net/validata/validata-badge/raw/master/badge_conf.toml
      - SHIELDS_IO_BASE_URL=https://img.shields.io/
      - SECRET_KEY=p4mBTNEHTbPx
    volumes:
      - /Users/alexandre/Developer/Etalab/schema/schema.data.gouv.fr/:/schemas/
