version: '3'

services:
  api:
    build:
      context: ./api
      # use this to pull validata from your own fork or another branch
      #args:
      #  VALIDATA_CORE_REPO: git+https://git.opendatafrance.net/abulte/validata-core.git@dev
      #  VALIDATA_API_REPO: git+https://git.opendatafrance.net/abulte/validata-api.git@dev
    ports:
      - 5600:5600
    environment:
      BADGE_CONFIG_URL: https://git.opendatafrance.net/validata/validata-badge/raw/master/badge_conf.toml
      SECRET_KEY: dev
  ui:
    build:
      context: ./ui
      # use this to pull validata from your own fork or another branch
      #args:
      #VALIDATA_CORE_REPO: git+https://git.opendatafrance.net/abulte/validata-core.git@dev
      #VALIDATA_UI_REPO: git+https://git.opendatafrance.net/abulte/validata-ui.git@etalab
    ports:
      - 5601:5601
    # use environment and volumes to point to a custom homepage_config.json
    environment:
      API_VALIDATE_ENDPOINT: http://api:5600/validate
      HOMEPAGE_CONFIG_FILE: /config/homepage_config.json
      SECRET_KEY: dev
      SHIELDS_IO_BASE_URL: https://img.shields.io/
    volumes:
     - ./config/:/config/
